# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "271fe345-6376-4ac0-a4b0-d9d1df7c56a0"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build your iOS app
  gym(
    # scheme: "YourScheme",
    export_method: "ad-hoc"
  )

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "9cbbab9300390959bd48b87d8497bc194a44486d",
    build_secret: "e65aac01986581f34df9e32439201e2132b16996854f18748bf3b8810506ef98"
  )
  slack(
       slack_url: "https://hooks.slack.com/services/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",
       message: "#{changelog}- see it at https://fabric.io/_/beta"
    )
end
